---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/sandboxtv/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
