<?php
$customerReviews = [
    [
        'source' => 'google',
        'source_label' => 'Google',
        'name' => 'Jay W.',
        'meta' => '48 Reviews',
        'date' => 'February 2026',
        'rating' => '5.0',
        'stars' => '★★★★★',
        'image' => '/assets/images/reviews/jay_weibel_google_review.png',
        'image_alt' => 'Portrait of Jay Weibel',
        'text' => 'Great Service. Got me in, fixed my rig, called, texted. What else could you want? Thanks, Titan Vans.',
    ],
    [
        'source' => 'google',
        'source_label' => 'Google',
        'name' => 'Tony S.',
        'meta' => '403 Reviews',
        'date' => 'September 2025',
        'rating' => '5.0',
        'stars' => '★★★★★',
        'image' => '/assets/images/reviews/tony_shouse_google_review.png',
        'image_alt' => 'Portrait of Tony Shouse',
        'text' => 'Extremely friendly, high quality service.',
    ],
    [
        'source' => 'google',
        'source_label' => 'Google',
        'name' => 'Lisa R.',
        'meta' => '214 Reviews',
        'date' => 'September 2025',
        'rating' => '5.0',
        'stars' => '★★★★★',
        'image' => '/assets/images/reviews/lisa_k_google_review.png',
        'image_alt' => 'Portrait of Lisa R.',
        'text' => 'Titan Vans did a fantastic job. They quickly, professionally, and expertly diagnosed and repaired a complicated problem we were experiencing with the solar system in our van. We were traveling through Boulder on our way back to Virginia where we knew we would find no experienced technicians. Titan worked us in quickly, kept us updated regularly during their inspection, and were able to repair the system on the same day for a very reasonable sum. The facility is state of the art and the employees show pride in their work. We couldn’t recommend Titan any more highly.',
    ],
    [
        'source' => 'google',
        'source_label' => 'Google',
        'name' => 'Bill A.',
        'meta' => '6 Reviews',
        'date' => 'October 2025',
        'rating' => '5.0',
        'stars' => '★★★★★',
        'image' => '/assets/images/reviews/bill_atkinson_google_review.png',
        'image_alt' => 'Portrait of Bill Atkinson',
        'text' => 'I own a 2023 Winnebago Revel built on a 2022 Mercedes Sprinter 2500. Both have their quirks, and I experienced them full scale recently while on the road for a month with at least a month (and many miles) to go. Revel. I\'ve been bedeviled by its electrical/house systems and understanding of them since owning. Technician Samuel looked them over, reset them - no issues, thankfully - then took all the time I needed to explain in simple terms what to look for when problems occur, best settings, and how best to use the systems when on and off grid. Sprinter. Cruise Control works when it feels like it. When it doesn\'t, dash displays "Active Distance Assist Inoperative" and "Active Brake Assist Unavailable." Maddening! Samuel reset this, and it worked the rest of the day yesterday...but won\'t work today. Oh well...I\'ll try to reset it myself on Samuel\'s advice. MANY THANKS and CUDOS to Titan Vans for taking me in short notice and fixing my issues in less than 2hrs.',
    ],
    [
        'source' => 'google',
        'source_label' => 'Google',
        'name' => 'Dylan B.',
        'meta' => '3 Reviews',
        'date' => 'August 2025',
        'rating' => '5.0',
        'stars' => '★★★★★',
        'image' => '/assets/images/reviews/dylan_beeson_google_review.png',
        'image_alt' => 'Portrait of Dylan Beeson',
        'text' => 'As a small business owner in the adventure travel space, I seek out other vendors who have honed their craft in service of their dream. Quality, Craftsmanship and value are vital to any vendor we work with because that is how we run our business. The team at Titan have been wonderful to work with.',
    ],
    [
        'source' => 'google',
        'source_label' => 'Google',
        'name' => 'PJ J.',
        'meta' => '3 Reviews',
        'date' => 'August 2025',
        'rating' => '5.0',
        'stars' => '★★★★★',
        'image' => '/assets/images/reviews/pj_jacobs_google_review.png',
        'image_alt' => 'Portrait of PJ Jacobs',
        'text' => 'Ryan went out of his way to help diagnose a Victron Energy Solar Charger problem. Again, thank you for all that you do! I would highly recommend Titan Vans!',
    ],
    [
        'source' => 'google',
        'source_label' => 'Google',
        'name' => 'Elizabeth H.',
        'meta' => '10 Reviews',
        'date' => 'March 2025',
        'rating' => '5.0',
        'stars' => '★★★★★',
        'image' => '/assets/images/reviews/elizabeth_holby_google_review.png',
        'image_alt' => 'Portrait of Elizabeth Holby',
        'text' => 'Excellent, timely, professional service. I needed my underseat webasto heater and solar electrical system serviced. I was traveling thru Denver area and they fit me in and evaluated and solved issues.',
    ],
    [
        'source' => 'google',
        'source_label' => 'Google',
        'name' => 'Dave P.',
        'meta' => '1 Review',
        'date' => 'March 2026',
        'rating' => '5.0',
        'stars' => '★★★★★',
        'image' => '/assets/images/reviews/dave_p_yelp_review.jpg',
        'image_alt' => 'Portrait of Dave P.',
        'text' => 'Titan Vans is a fantastic company. Their van builds are top-notch and extremely functional. Can’t say enough great things about this business.',
    ],
    [
        'source' => 'google',
        'source_label' => 'Google',
        'name' => 'Jeanie N.',
        'meta' => '70 Reviews',
        'date' => 'January 2026',
        'rating' => '5.0',
        'stars' => '★★★★★',
        'image' => '/assets/images/reviews/jeane_miel_google_review.png',
        'image_alt' => 'Portrait of Jeanie Neal',
        'text' => 'Came all the way from Omaha and it was worth the drive. Fast, efficient, friendly service from first contact through the payment.',
    ],
    [
        'source' => 'google',
        'source_label' => 'Google',
        'name' => 'Kyle Y.',
        'meta' => '2 Reviews',
        'date' => 'March 2026',
        'rating' => '5.0',
        'stars' => '★★★★★',
        'image' => '/assets/images/reviews/default_user_avatar_yelp.png',
        'image_alt' => 'Portrait of Kyle Yoder',
        'text' => 'Jason and the team did a great job of fitting me in quickly and resolving my heater installation issues. I’ll be working with them again in the future.',
    ],
    [
        'source' => 'google',
        'source_label' => 'Google',
        'name' => 'Paulette M.',
        'meta' => '1 Review',
        'date' => 'January 2026',
        'rating' => '5.0',
        'stars' => '★★★★★',
        'image' => '/assets/images/reviews/default_user_avatar_yelp.png',
        'image_alt' => 'Portrait of Paulette Medley',
        'text' => 'Titan Van is a wonderful company, whose has done a great job with my van, exceeded my expectations, appreciate their fabulous work over the years.',
    ],
];