<?php

$popularServiceCards = [
    [
        'id' => 'service-a',
        'name' => 'Service A',
        'subtitle' => 'General Maintenance',
        'price' => '$838.99',
        'image' => '/assets/images/sprinter-service-ab.png',
        'alt' => 'Service A image',
        'description' => 'A focused essential maintenance service for your camper van that keeps your van running clean, safe, and road-ready with fresh synthetic oil, filter replacement, fluid top-offs, system reset, and a full inspection.',
        'time' => '1-2 hours',
        'models' => ['sprinter-144', 'sprinter-170', 'transit-148', 'promaster-159'],
        'filter_models' => ['Sprinter', 'Transit', 'ProMaster'],
        'recent' => '2026-03-15',
        'popularity' => 18,
        'search_terms' => 'maintenance inspection fluids drivetrain',
        'badge' => 'Popular',
        'button_class' => 'service-add',
    ],
    [
        'id' => 'service-b',
        'name' => 'Service B',
        'subtitle' => 'Premium Service',
        'price' => '$1,153.99',
        'image' => '/assets/images/sprinter-service-ab.png',
        'alt' => 'Service B image',
        'description' => 'A more complete maintenance package for your camper van that includes everything in Service A, plus engine air, cabin, and fuel filter replacements for stronger performance, cleaner airflow, and added long-term reliability.',
        'time' => '2–3 hours',
        'models' => ['sprinter-144', 'sprinter-170', 'transit-148', 'promaster-159'],
        'filter_models' => ['Sprinter', 'Transit', 'ProMaster'],
        'recent' => '2026-03-12',
        'popularity' => 27,
        'search_terms' => 'premium service full check diagnostic',
        'badge' => 'Recommended',
        'button_class' => 'service-add',
    ],
    [
        'id' => 'tire-rotation',
        'name' => 'Tire Rotation',
        'subtitle' => 'Wheel & Tire Service',
        'price' => '$250.99',
        'image' => '/assets/images/sprinter-tire-rotation.jpg',
        'alt' => 'Tire rotation service image',
        'description' => 'Our tire rotation service may be added to any of the Service packages. Regular tire rotations are essential for maintaining even tread wear, improving handling, and extending the life of your tires.',
        'time' => '1 hour',
        'models' => ['sprinter-144', 'sprinter-170', 'transit-148', 'promaster-159'],
        'filter_models' => ['Sprinter', 'Transit', 'ProMaster'],
        'recent' => '2026-03-10',
        'popularity' => 42,
        'search_terms' => 'tires wheels rotate balancing alignment wear',
        'badge' => 'Best Seller',
        'button_class' => 'service-add',
    ],
    [
        'id' => 'wheel-alignment',
        'name' => 'Wheel Alignment',
        'subtitle' => 'Suspension & Steering',
        'price' => '$250.99',
        'image' => '/assets/images/sprinter-wheel-alignment.jpg',
        'alt' => 'Wheel alignment service image',
        'description' => 'Ensure your camper van drives smoothly, efficiently, and safely with our professional alignment service. Proper wheel alignment is essential for maintaining even tire wear, improving fuel efficiency, and enhancing overall handling.',
        'time' => '1-2 hours',
        'models' => ['sprinter-144', 'sprinter-170', 'transit-148', 'promaster-159'],
        'filter_models' => ['Sprinter', 'Transit', 'ProMaster'],
        'recent' => '2026-03-08',
        'popularity' => 31,
        'search_terms' => 'alignment steering suspension tires handling',
        'button_class' => 'service-add',
    ],
];

$upgradeCards = [
    [
        'id' => 'upgrade-a',
        'name' => 'Upgrade A',
        'subtitle' => 'Comfort Upgrade',
        'price' => '$838.99',
        'image' => '/assets/images/sprinter-service-ab.png',
        'alt' => 'Upgrade A image',
        'description' => 'Description',
        'time' => 'Half day',
        'models' => ['sprinter-144', 'sprinter-170', 'transit-148', 'promaster-159'],
        'filter_models' => ['Sprinter', 'Transit', 'ProMaster'],
        'recent' => '2026-03-16',
        'popularity' => 14,
        'search_terms' => 'comfort ride interior suspension',
        'badge' => 'New',
        'button_class' => 'upgrade-add',
    ],
    [
        'id' => 'upgrade-b',
        'name' => 'Upgrade B',
        'subtitle' => 'Performance Upgrade',
        'price' => '$1,153.99',
        'image' => '/assets/images/sprinter-service-ab.png',
        'alt' => 'Upgrade B image',
        'description' => 'Description',
        'time' => 'Full day',
        'models' => ['sprinter-144', 'sprinter-170', 'transit-148', 'promaster-159'],
        'filter_models' => ['Sprinter', 'Transit', 'ProMaster'],
        'recent' => '2026-03-14',
        'popularity' => 22,
        'search_terms' => 'performance handling upgrade stability',
        'badge' => 'Recommended',
        'button_class' => 'upgrade-add',
    ],
    [
        'id' => 'upgrade-tire-rotation',
        'name' => 'Tire Rotation Upgrade',
        'subtitle' => 'Wheel Service',
        'price' => '$250.99',
        'image' => '/assets/images/sprinter-tire-rotation.jpg',
        'alt' => 'Tire rotation upgrade image',
        'description' => 'Description',
        'time' => '1 hour',
        'models' => ['sprinter-144', 'sprinter-170', 'transit-148', 'promaster-159'],
        'filter_models' => ['Sprinter', 'Transit', 'ProMaster'],
        'recent' => '2026-03-09',
        'popularity' => 11,
        'search_terms' => 'tires wheels service upgrade',
        'button_class' => 'upgrade-add',
    ],
    [
        'id' => 'upgrade-wheel-alignment',
        'name' => 'Wheel Alignment Upgrade',
        'subtitle' => 'Handling Upgrade',
        'price' => '$250.99',
        'image' => '/assets/images/sprinter-wheel-alignment.jpg',
        'alt' => 'Wheel alignment upgrade image',
        'description' => 'Description',
        'time' => '1.5 hours',
        'models' => ['sprinter-144', 'sprinter-170', 'transit-148'],
        'filter_models' => ['Sprinter', 'Transit'],
        'recent' => '2026-03-07',
        'popularity' => 9,
        'search_terms' => 'alignment steering handling upgrade',
        'button_class' => 'upgrade-add',
    ],
    [
        'id' => 'upgrade-c',
        'name' => 'Upgrade C',
        'subtitle' => 'Off-Road Upgrade',
        'price' => '$1,499.99',
        'image' => '/assets/images/sprinter-service-ab.png',
        'alt' => 'Upgrade C image',
        'description' => 'Description',
        'time' => 'Full day',
        'models' => ['sprinter-144', 'sprinter-170'],
        'filter_models' => ['Sprinter'],
        'recent' => '2026-03-13',
        'popularity' => 19,
        'search_terms' => 'off road suspension terrain handling',
        'badge' => 'Top Pick',
        'button_class' => 'upgrade-add',
    ],
    [
        'id' => 'upgrade-d',
        'name' => 'Upgrade D',
        'subtitle' => 'Touring Upgrade',
        'price' => '$1,299.99',
        'image' => '/assets/images/sprinter-service-ab.png',
        'alt' => 'Upgrade D image',
        'description' => 'Description',
        'time' => 'Full day',
        'models' => ['transit-148', 'promaster-159'],
        'filter_models' => ['Transit', 'ProMaster'],
        'recent' => '2026-03-11',
        'popularity' => 16,
        'search_terms' => 'touring travel comfort road trip',
        'button_class' => 'upgrade-add',
    ],
];

$appServiceCards = $popularServiceCards;